spring:
  application:
    name: zp-user-module
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        group: zp
        server-addr: localhost:8848
        namespace: 31566b11-faba-4430-ab6c-353aa99c9874
        username: nacos
        password: 123456
        file-extension: yml
      discovery:
        group: zp
        server-addr: localhost:8848
        namespace: 31566b11-faba-4430-ab6c-353aa99c9874
        username: nacos
        password: 123456
        ip: 127.0.0.1
    openfeign:
      lazy-attributes-resolution: true
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?group=zp

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    hikari:
      max-lifetime: 60000



server:
  port: 6050

feign:
  sentinel:
    enabled: true

zp:
  jwt:
    salt: sdadaddadada
    expires: 1000000000
  security:
    write-list:
      - /ws/web/connect