spring:
  application:
    name: zp-system-module
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        group: zp
        server-addr: 101.42.12.133:8848
#        namespace: 31566b11-faba-4430-ab6c-353aa99c9874
        namespace: 1379388b-aed1-4082-8ed2-54699a4cc9d4
        username: nacos
        password: nacos123456
        file-extension: yml
        enabled: true
      discovery:
        group: zp
        server-addr: 101.42.12.133:8848
        namespace: 1379388b-aed1-4082-8ed2-54699a4cc9d4
#        namespace: 31566b11-faba-4430-ab6c-353aa99c9874
        username: nacos
        password: nacos123456
        ip: 127.0.0.1
    openfeign:
      lazy-attributes-resolution: true
      compression:
        request:
          enabled: true
        response:
          enabled:  true
      okhttp:
        enabled: true


  config:
    import:
      - optional:nacos:zp-config?group=zp
      - optional:nacos:zp-actuator-config.yml?group=zp
      - optional:nacos:zp-mvc-normal?group=zp

server:
  port: 6168
  compression:
    enabled: true