spring:
  application:
    name: zp-storage-v2-module
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        group: zp
        server-addr: 101.42.12.133:8848
        namespace: 1379388b-aed1-4082-8ed2-54699a4cc9d4
        username: nacos
        password: nacos123456
        file-extension: yml
        enabled: true
      discovery:
        group: zp
        server-addr: 101.42.12.133:8848
        namespace: 1379388b-aed1-4082-8ed2-54699a4cc9d4
        username: nacos
        password: nacos123456
        ip: 127.0.0.1
    openfeign:
      lazy-attributes-resolution: true
      compression:
        request:
          enabled: true
        response:
            enabled:  true
    sentinel:
      enabled: false
  config:
    import:
      - optional:nacos:zp-mysql-config.yml?group=zp
      - optional:nacos:zp-redis-config.yml?group=zp
      - optional:nacos:zp-config?group=zp
      - optional:nacos:zp-actuator-config.yml?group=zp
      - optional:nacos:zp-mvc-normal?group=zp
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
server:
  port: 6101
  compression:
    enabled: true
zp:
  storage:
    v2:
      config:
        MINIO: |
          host: 127.0.0.1
          port: 9000
        QINIU: |
          host: 127.0.0.1
          port: 8000


