spring:
  application:
    name: zp-storagecalculation-module
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        group: zp
        server-addr: 101.42.12.133:8848
        namespace: 31566b11-faba-4430-ab6c-353aa99c9874
        username: nacos
        password: nacos123456
        file-extension: yml
        enabled: false
      discovery:
        group: zp
        server-addr: 101.42.12.133:8848
        namespace: 31566b11-faba-4430-ab6c-353aa99c9874
        username: nacos
        password: nacos123456
        ip: 127.0.0.1
    openfeign:
      lazy-attributes-resolution: true
    sentinel:
      enabled: false

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    hikari:
      max-lifetime: 60000
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-a7tnayym.sql.tencentcdb.com:21449/zp?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&useAffectedRows=true&rewriteBatchedStatements=true
    username: admin01
    password: CZPczp666...
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  data:
    redis:
      database: 3
      host: 82.156.191.218
      port: 6379
      password: admin123654
      connect-timeout: 10000







server:
  port: 6100

feign:
  sentinel:
    enabled: true

zp:
  jwt:
    salt: sdadaddadada
    expires: 1000000000
  logger-push:
    es-host: 101.42.12.133
    ex-port: 9200
    es-username: elastic
    es-password: Abcd1234....
#  security:
#    write-list:
#      - /api/web/getFilePublic

  storage:
    location: ./filetemp/a/
#    hardwareUid: qqaacc

management:
  health:
    elasticsearch:
      enabled: false
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: "*"
