spring:
  application:
    name: zp-storagecalculation-module
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        group: zp
        server-addr: 101.42.12.133:8848
        namespace: 31566b11-faba-4430-ab6c-353aa99c9874
        username: nacos
        password: nacos123456
        file-extension: yml
        enabled: true
      discovery:
        group: zp
        server-addr: 101.42.12.133:8848
        namespace: 31566b11-faba-4430-ab6c-353aa99c9874
        username: nacos
        password: nacos123456
        ip: 127.0.0.1
    openfeign:
      lazy-attributes-resolution: true
    sentinel:
      enabled: false
  config:
    import:
      - optional:nacos:zp-mysql-config.yml?group=zp
      - optional:nacos:zp-redis-config.yml?group=zp
      - optional:nacos:zp-config?group=zp
      - optional:nacos:zp-actuator-config.yml?group=zp
      - optional:nacos:zp-mvc-normal?group=zp
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
server:
  port: 6100
zp:
  storage:
    location: ./filetemp/a/
