
name: gateway-build

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github  
        settings-path: ${{ github.workspace }} 

    - name: gradle cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew bootJar
        
    - name: Upload latest artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: gateway-1.0-SNAPSHOT.jar
        path: ./gateway/build/libs/gateway-1.0-SNAPSHOT.jar
        if-no-files-found: error
        
        
    - name: upload file to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:  
        username: ${{USER}}   
        server: ${{ HOST }} 
        ssh_private_key: ${{ RSA_KEY }} 
        local_path: ./gateway/build/libs/*
        remote_path: /opt/software/zp/gateway/jarfile

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
